/* Amoria Admission System - GitHub Pages + Firebase Realtime Database */
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.database();
const grades = ["الأول الابتدائي","الثاني الابتدائي","الثالث الابتدائي","الرابع الابتدائي","الخامس الابتدائي","السادس الابتدائي","الأول المتوسط","الثاني المتوسط","الثالث المتوسط","الأول الثانوي","الثاني الثانوي","الثالث الثانوي"];
const $ = s => document.querySelector(s);
const $$ = s => Array.from(document.querySelectorAll(s));
function esc(v){return String(v||'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function uid(){return auth.currentUser?.uid||'unknown'}
function now(){return new Date().toLocaleString('ar-SA')}
function go(p){location.href=p}
function requireAuth(){auth.onAuthStateChanged(u=>{if(!u && !location.pathname.endsWith('index.html') && !location.pathname.endsWith('/')) go('index.html')})}
function initLogin(){const f=$('#loginForm'); if(!f)return; auth.onAuthStateChanged(u=>{if(u)go('dashboard.html')}); f.onsubmit=e=>{e.preventDefault(); $('#loginMsg').textContent='جاري تسجيل الدخول...'; auth.signInWithEmailAndPassword($('#email').value,$('#password').value).then(()=>go('dashboard.html')).catch(err=>$('#loginMsg').textContent='تعذر الدخول: '+err.message)}}
function logout(){auth.signOut().then(()=>go('index.html'))}
async function getSettings(){const snap=await db.ref('settings').once('value');return snap.val()||{schoolName:'ثانوية عمورية',committeeName:'لجنة القبول والتسجيل بثانوية عمورية',signer:'عضو لجنة القبول بمدرسة عمورية المكلف',letterText:'تحقيقاً لأهداف الإدارة العامة للتعليم بمحافظة جدة نحو استقرار الميدان، وما يتوفر لدى اللجنة من بيانات الطاقة الاستيعابية. نأمل منكم التعاون في قبول الطالب أدناه بمدرستكم العامرة بحسب الأنظمة والتعليمات المنظمة للقبول.'}}
async function saveSettings(e){e.preventDefault();const data={schoolName:$('#schoolName').value,committeeName:$('#committeeName').value,signer:$('#signer').value,letterText:$('#letterText').value};await db.ref('settings').set(data);$('#saveMsg').textContent='تم حفظ الإعدادات بنجاح'}
async function initSettings(){if(!$('#settingsForm'))return;requireAuth();const s=await getSettings();$('#schoolName').value=s.schoolName||'';$('#committeeName').value=s.committeeName||'';$('#signer').value=s.signer||'';$('#letterText').value=s.letterText||'';$('#settingsForm').onsubmit=saveSettings}
function fillGrades(){const sel=$('#grade'); if(!sel)return; sel.innerHTML='<option value="">اختر الصف</option>'+grades.map(g=>`<option>${g}</option>`).join('')}
async function addStudent(e){e.preventDefault(); const civilId=$('#civilId').value.trim(); const exists=await db.ref('students').orderByChild('civilId').equalTo(civilId).once('value'); if(exists.exists()){alert('السجل المدني موجود مسبقًا');return} const data={school:$('#school').value.trim(),studentName:$('#studentName').value.trim(),civilId,nationality:$('#nationality').value.trim(),grade:$('#grade').value,phone:$('#phone').value.trim(),notes:$('#notes').value.trim(),status:'تم إصدار الخطاب',archived:false,createdAt:Date.now(),createdAtText:now(),createdBy:auth.currentUser?.email||''}; const ref=await db.ref('students').push(data); await db.ref('logs').push({type:'add_student',studentId:ref.key,by:data.createdBy,at:Date.now(),atText:now()}); $('#studentForm').reset(); alert('تم حفظ الطالب بنجاح'); loadStudents();}
async function loadStudents(){if(!$('#studentsBody'))return; const q=($('#searchInput')?.value||'').trim(); const showArchived=$('#showArchived')?.checked; const snap=await db.ref('students').orderByChild('createdAt').once('value'); const rows=[]; snap.forEach(ch=>{const s={id:ch.key,...ch.val()}; if(!showArchived && s.archived)return; const text=[s.school,s.studentName,s.civilId,s.nationality,s.grade,s.phone].join(' '); if(q && !text.includes(q))return; rows.push(s)}); rows.reverse(); $('#studentsBody').innerHTML=rows.map(s=>`<tr class="${s.archived?'archived':''}"><td>${esc(s.studentName)}</td><td>${esc(s.civilId)}</td><td>${esc(s.school)}</td><td>${esc(s.grade)}</td><td><span class="badge">${esc(s.status||'جديد')}</span></td><td>${esc(s.createdBy)}</td><td class="actions"><a class="btn small" href="letter.html?id=${s.id}">خطاب</a><button class="btn small secondary" onclick="editStudent('${s.id}')">تعديل</button><button class="btn small danger" onclick="archiveStudent('${s.id}',${s.archived?false:true})">${s.archived?'استعادة':'أرشفة'}</button></td></tr>`).join('')||'<tr><td colspan="7">لا توجد بيانات</td></tr>'}
async function editStudent(id){const snap=await db.ref('students/'+id).once('value');const s=snap.val(); if(!s)return; const name=prompt('اسم الطالب',s.studentName); if(name===null)return; const school=prompt('اسم المدرسة',s.school); if(school===null)return; await db.ref('students/'+id).update({studentName:name,school,updatedAt:Date.now(),updatedBy:auth.currentUser?.email||''}); loadStudents()}
async function archiveStudent(id,state){await db.ref('students/'+id).update({archived:state,archivedAt:Date.now(),archivedBy:auth.currentUser?.email||''}); loadStudents()}
async function initStudents(){if(!$('#studentForm'))return; requireAuth(); fillGrades(); $('#studentForm').onsubmit=addStudent; $('#searchInput').oninput=loadStudents; $('#showArchived').onchange=loadStudents; loadStudents()}
async function initDashboard(){if(!$('#stats'))return; requireAuth(); const snap=await db.ref('students').once('value'); let total=0,active=0,archived=0,schools=new Set(); snap.forEach(ch=>{const s=ch.val(); total++; if(s.archived)archived++; else active++; if(s.school)schools.add(s.school)}); $('#stats').innerHTML=`<div class="card stat"><b>${total}</b><span>إجمالي الطلاب</span></div><div class="card stat"><b>${active}</b><span>الطلبات النشطة</span></div><div class="card stat"><b>${archived}</b><span>الأرشيف</span></div><div class="card stat"><b>${schools.size}</b><span>عدد المدارس</span></div>`; const recent=await db.ref('students').orderByChild('createdAt').limitToLast(8).once('value'); const arr=[]; recent.forEach(c=>arr.push(c.val())); arr.reverse(); $('#recentBody').innerHTML=arr.map(s=>`<tr><td>${esc(s.studentName)}</td><td>${esc(s.school)}</td><td>${esc(s.grade)}</td><td>${esc(s.createdAtText)}</td></tr>`).join('')||'<tr><td colspan="4">لا توجد بيانات</td></tr>'}
async function initLetter(){if(!$('#letterContent'))return; requireAuth(); const id=new URLSearchParams(location.search).get('id'); const st=await getSettings(); if(!id){$('#letterContent').innerHTML='لم يتم اختيار طالب';return} const snap=await db.ref('students/'+id).once('value'); const s=snap.val(); if(!s){$('#letterContent').innerHTML='الطالب غير موجود';return} $('#letterContent').innerHTML=`<div class="letter-box">${esc(st.committeeName)}</div><p>المكرم مدير مدرسة / <b>${esc(s.school)}</b> المحترم</p><p>السلام عليكم ورحمة الله وبركاته،</p><p>${esc(st.letterText)}</p><table><tr><th>اسم الطالب</th><td>${esc(s.studentName)}</td></tr><tr><th>السجل المدني</th><td>${esc(s.civilId)}</td></tr><tr><th>الجنسية</th><td>${esc(s.nationality)}</td></tr><tr><th>الصف</th><td>${esc(s.grade)}</td></tr></table><p>وتقبلوا فائق التحية والتقدير.</p><div class="signature"><b>${esc(st.signer)}</b><br>الاسم: ........................<br>التوقيع: ......................</div>`}
function exportCSV(){db.ref('students').once('value').then(snap=>{let csv='اسم الطالب,السجل المدني,المدرسة,الجنسية,الصف,الجوال,تاريخ الإضافة\n'; snap.forEach(ch=>{const s=ch.val(); csv += [s.studentName,s.civilId,s.school,s.nationality,s.grade,s.phone,s.createdAtText].map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(',')+'\n'}); const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='students.csv';a.click()})}
window.logout=logout; window.editStudent=editStudent; window.archiveStudent=archiveStudent; window.exportCSV=exportCSV;
document.addEventListener('DOMContentLoaded',()=>{initLogin();initDashboard();initStudents();initSettings();initLetter()});
